### PR TITLE
Feat google

### PR DESCRIPTION
**Pull request by cursorweb**
This adds the google style guide.

With the google style guide it makes it super easy and convenient for multiple collaborators to make code that is consistent.

It also makes it required for your code to pass the google style guide which should be pretty easy to do

###### *I like how there's no merge conflicts how convenient*

### CODE REVIEW

**Review by mike-weiner — COMMENTED** [review]
These changes look to be stylistic. I did run this branch locally and there did not seem to be any breaking changes. 

https://github.com/Minnesota-Computer-Club/MCC-Website/blob/2d57df4feea7c9f5708964a161355f797fa214d3/README.md?plain=1#L50

Can you please look at that line in the README and make sure that is the correct command to run? Please add any other commands that we might need to know about as well.

**Comment by cursorweb** [comment]
yes this is purely so we can have files that have the same indentation level and follow the same code guidelines

and i'll add these other commands:
```sh
npm run lint # check if linting is successful
npm run lint -- --fix # fix any autofixable problems
```

**Review by mike-weiner — APPROVED** [review]
Ran locally and things run fine. All changes are related to using Google Style Guidelines.

**Comment by cursorweb** [comment]
sounds good!

**Pull request merged**
