### PR TITLE
Fixed ordering of combined leaderboard - Recalculated local scores

### PR DESCRIPTION
**Pull request by NifleySnifley**
Pretty much just adds one thing: `regenLocalScores`
Recalculates the local score for each user in a larger combined individual leaderboard so the ordering is correct by using the same formula that the AOC official leaderboard does:
> For N users
> The first user to get each star gets N points
> the second gets N-1, and so on

**tl;dr**: Arbitrarily large leaderboards created from combining multiple official leaderboards are now correctly scored and ordered

### CODE REVIEW

**Comment by KennyHarrer** [comment]
please figure out why the sections are not aligned and then I will merge

**Comment by KennyHarrer** [comment]
please fix merge issues causes by cursorweb with styling and I will merge

**Comment by NifleySnifley** [comment]
Seems to work fine, ready to merge.

**Comment by KennyHarrer** [comment]
im trusting you

**Pull request merged**
