### PR TITLE
Add Countdowns to Leaderboards

### PR DESCRIPTION
**Pull request by mike-weiner**
This PR addresses #19:

- This PR adds a new `Countdown` component. 
- The `date-fns` library was added for convince for date manipulation.
- 2 countdowns have been added to the Leaderboard component to display (1) a countdown to the next puzzle unlocking and (2) a countdown to the end of our competition on New Year's Eve at midnight.

### CODE REVIEW

**Comment by cursorweb** [comment]
One question, why does gdc have so little stars?
image
compare to mncomputerclub website:
image

**Comment by cursorweb** [comment]
wait never mind that's an issue with both websites

**Comment by NifleySnifley** [comment]
Tested, seems to work alright, just 2 things to note:
 
- Someone will have to make sure to run `npm i` before the cron job runs to update it or it will break.
- It seems to take a little bit of time to load the timers, which is a tad annoying.

**Comment by mike-weiner** [comment]
Good point with the `npm i` being needed.  And yes, the countdowns do take 1 second to load. This is to allow React to set state and load the component and page.

**Review by KennyHarrer — CHANGES_REQUESTED** [review]
I would shorten the suffix so its more mobile friendly, and move this in to the statistics section. Other than that it looks great!

**Comment by mike-weiner** [comment]
I have pushed up my local changes. Padding on the `countdownWrapper` were reduced from `1rem` down to `0.25rem`.

Screenshot-2022-12-05-09 40 58AM

**Comment by KennyHarrer** [comment]
resolve conflicts and ill merge! :)

**Pull request merged**
